version: "3.9"
services:
  python_app:
      build:
        context: .
        dockerfile: Dockerfile
      depends_on:
        - mongo
        - redis
      links:
        - mongo
        - redis
     
      
  redis:
    image: redis
  mongo:
    image: mongo
    ports:
      - 27017:27017



  
